### ISSUE TITLE
Virus total doesn't work [Bug]

### ISSUE THREAD

**Issue by TechnicPepijn** [FreeTechnologies/FreeDiscord#5]
It just gives a error. Either the list is not right it receives from the API or the key isn't right.

**Comment by recallwhoiam** [comment]
I have the key in there correctly so something isn't going as planned.
Here is the error:
```Ignoring exception in command scan_url:
Traceback (most recent call last):
  File "/home/recall/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/recall/FreeDiscord/cogs/vt_scan.py", line 55, in scan_url
    parsed = vt_json_parsing(response)
  File "/home/recall/FreeDiscord/cogs/vt_scan.py", line 12, in vt_json_parsing
    detections = detections[1]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/recall/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/recall/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/recall/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range```

**Comment by odysseus443** [comment]
I committed a fix.

**Comment by SKBotNL** [comment]
Currently testing

**Comment by SKBotNL** [comment]
Fixed in newest release
